### ISSUE TITLE
How to use serde with ndarray to parse json?

### ISSUE THREAD

**Issue by wangm23456** [rust-ndarray/ndarray#1168]
cargo:

```toml
[dependencies]
ndarray = {version = "0.15", features = ["serde", "rayon"]}
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"]}
```

```rust

#[derive(Serialize, Deserialize, Debug)]
struct myst{
    array: Array2<f32>,
}

#[test]
fn test_json() {
    let pathbuf = PathBuf::from("/path/to/test.json");
    let mut file = File::open(pathbuf).unwrap();
    let mut data = String::new();
    match file.read_to_string(&mut data) {
        Err(e) => panic!("{}",e),
        Ok(_) => {}
    }
    let v:  myst = serde_json::from_str(&data).unwrap();
    println!("{:?}", v);
}
```

the json is 
```json

{
"array": [
    [1,2,3],
    [4,5,6]]
}

```

but I get error:

> thread 'tests::test_json' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: sequence, expected u8", line: 3, column: 4)'
